# Host: localhost:3307  (Version: 5.0.27-community-nt)
# Date: 2019-06-16 14:14:13
# Generator: MySQL-Front 5.3  (Build 4.205)

/*!40101 SET NAMES latin1 */;

#
# Structure for table "select_bank"
#

DROP TABLE IF EXISTS `select_bank`;
CREATE TABLE `select_bank` (
  `id` int(11) NOT NULL auto_increment,
  `ifsc` varchar(45) default NULL,
  `bank_id` varchar(45) default NULL,
  `branch` varchar(45) default NULL,
  `city` varchar(45) default NULL,
  `district` varchar(45) default NULL,
  `state` varchar(45) default NULL,
  `bank_name` varchar(45) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

#
# Data for table "select_bank"
#

INSERT INTO `select_bank` VALUES (1,'ABHY0065001','60','RTGS-HO','MUMBAI','GREATER MUMBAI','MAHARASHTRA','ABHYUDAYA COOPERATIVE BANK LIMITED'),(2,'ABHY0065002','60','ABHYUDAYA NAGAR','MUMBAI','GREATER MUMBAI','MAHARASHTRA','ABHYUDAYA COOPERATIVE BANK LIMITED'),(3,'BARB0THANAX','4','THANE WEST BRANCH','MUMBAI','MUMBAI','MAHARASHTRA','BANK OF BARODA'),(4,'BARB0THAVIL','4','THAKUR VILLAGE  MUMBAI','MUMBAI','MUMBAI','MAHARASHTRA','BANK OF BARODA'),(5,'CNRB0000223','3','KAKAD MARKET  MUMBAI','MUMBAI','GREATER BOMBAY','MAHARASHTRA','CANARA BANK'),(6,'CNRB0000224','3','VILE PARLE EAST  MUMBAI','MUMBAI','GREATER BOMBAY','MAHARASHTRA','CANARA BANK'),(7,'CNRB0000225','3','MALAD WEST  MUMBAI','MUMBAI','GREATER BOMBAY','MAHARASHTRA','CANARA BANK'),(8,'DCBL0000043','57','FORT','MUMBAI','GREATER MUMBAI','MAHARASHTRA','DCB BANK LIMITED'),(9,'DCBL0000053','57','SABOO SIDDIQUE','MUMBAI','MUMBAI','MAHARASHTRA','DCB BANK LIMITED'),(10,'HDFC0000667','5','MUMBAI - AKRULI ROAD','MUMBAI','GREATER MUMBAI','MAHARASHTRA','HDFC BANK');

#
# Structure for table "select_bank1"
#

DROP TABLE IF EXISTS `select_bank1`;
CREATE TABLE `select_bank1` (
  `id` int(11) NOT NULL auto_increment,
  `ifsc` varchar(45) default NULL,
  `bank_id` varchar(45) default NULL,
  `branch` varchar(45) default NULL,
  `city` varchar(45) default NULL,
  `district` varchar(45) default NULL,
  `state` varchar(45) default NULL,
  `bank_name` varchar(45) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

#
# Data for table "select_bank1"
#

INSERT INTO `select_bank1` VALUES (11,'HDFC0000668','5','MUMBAI - SAHAR ROAD','MUMBAI','GREATER MUMBAI','MAHARASHTRA','HDFC BANK'),(12,'KAIJ0000020','90','MULUND','MUMBAI','MUMBAI','MAHARASHTRA','KARNATAKA BANK LIMITED'),(13,'KARB0000079','36','CORPORATE FINANCE BRANCH','MUMBAI','MUMBAI','MAHARASHTRA','KARNATAKA BANK LIMITED'),(14,'LAVB0000220','49','DHAMTARI','MUMBAI','MUMBAI','MAHARASHTRA','LAXMI VILAS BANK'),(15,'LAVB0000422','49','MALAD WEST','MUMBAI','MUMBAI','MAHARASHTRA','LAXMI VILAS BANK'),(16,'LAVB0000852','49','MUMBAI SERVICE BRANCH','MUMBAI','GREATER BOMBAY','MAHARASHTRA','LAXMI VILAS BANK'),(17,'MAHB0000329','23','LALBAUG  MUMBAI','MUMBAI','GREATER BOMBAY','MAHARASHTRA','BANK OF MAHARASHTRA'),(18,'MAHB0000334','23','GRANT ROAD  MUMBAI','MUMBAI','GREATER BOMBAY','MAHARASHTRA','BANK OF MAHARASHTRA'),(19,'NKGS0000016','65','KARWAR','MUMBAI','KARWAR','MAHARASHTRA','NKGSB COOPERATIVE BANK LIMITED'),(20,'NKGS0000018','65','MAROL','MUMBAI','MUMBAI','MAHARASHTRA','NKGSB COOPERATIVE BANK LIMITED');

#
# Structure for table "select_bank2"
#

DROP TABLE IF EXISTS `select_bank2`;
CREATE TABLE `select_bank2` (
  `id` int(11) NOT NULL auto_increment,
  `ifsc` varchar(45) default NULL,
  `bank_id` varchar(45) default NULL,
  `branch` varchar(45) default NULL,
  `city` varchar(45) default NULL,
  `district` varchar(45) default NULL,
  `state` varchar(45) default NULL,
  `bank_name` varchar(45) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

#
# Data for table "select_bank2"
#

INSERT INTO `select_bank2` VALUES (21,'ORBC0000023','19','FORT','MUMBAI','MUMBAI','MAHARASHTRA','ORIENTAL BANK OF COMMERCE'),(22,'ORBC0000643','19','STOCK EXCHANGE','MUMBAI','MUMBAI','MAHARASHTRA','ORIENTAL BANK OF COMMERCE'),(23,'ORBC0100000','19','RTGS-HO','MUMBAI','MUMBAI','MAHARASHTRA','ORIENTAL BANK OF COMMERCE'),(24,'PMCB0000058','62','GURUDWARA RAOLI CAMP','MUMBAI','GREATER BOMBAY','MAHARASHTRA','PUNJAB AND MAHARSHTRA COOPERATIVE BANK'),(25,'PMCB0000059','62','MAROL ANDHERI EAST','MUMBAI','GREATER BOMBAY','MAHARASHTRA','PUNJAB AND MAHARSHTRA COOPERATIVE BANK'),(26,'SAHE0000006','123','KALAMBOLI','MUMBAI','GREATER BOMBAY','MAHARASHTRA','SAHEBRAO DESHMUKH COOPERATIVE BANK'),(27,'TJSB0000051','66','CHARKOP BRANCH','MUMBAI','GREATER BOMBAY','MAHARASHTRA','TJSB SAHAKARI BANK LTD'),(28,'TJSB0000053','66','BHANDUP BRANCH','MUMBAI','GREATER BOMBAY','MAHARASHTRA','TJSB SAHAKARI BANK LTD'),(29,'UBIN0531880','9','OPERA HOUSE - MUMBAI','MUMBAI','GREATER BOMBAY','MAHARASHTRA','UNION BANK OF INDIA'),(30,'UBIN0531898','9','PEDDAR ROAD - MUMBAI','MUMBAI','GREATER BOMBAY','MAHARASHTRA','UNION BANK OF INDIA');

#
# Structure for table "select_bank3"
#

DROP TABLE IF EXISTS `select_bank3`;
CREATE TABLE `select_bank3` (
  `id` int(11) NOT NULL auto_increment,
  `ifsc` varchar(45) default NULL,
  `bank_id` varchar(45) default NULL,
  `branch` varchar(45) default NULL,
  `city` varchar(45) default NULL,
  `district` varchar(45) default NULL,
  `state` varchar(45) default NULL,
  `bank_name` varchar(45) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

#
# Data for table "select_bank3"
#

INSERT INTO `select_bank3` VALUES (31,'VIJB0009502','22','RTGS-HO','MUMBAI','MUMBAI','MAHARASHTRA','VIJAYA BANK'),(32,'VIJB0009513','22','OVERSEAS BRANCH SANTACRUZ','MUMBAI','MUMBAI','MAHARASHTRA','VIJAYA BANK'),(33,'YESB0000164','17','BORIVALI  MUMBAI','MUMBAI','GREATER BOMBAY','MAHARASHTRA','YES BANK'),(34,'YESB0000189','17','LAMINGTON ROAD  MUMBAI','MUMBAI','GREATER BOMBAY','MAHARASHTRA','YES BANK'),(35,'ZCBL0000010','119','MAHIM','MUMBAI','MUMBAI','MAHARASHTRA','THE ZOROASTRIAN  BANK'),(36,'ZCBL0000011','119','BORIVALI','MUMBAI','MUMBAI','MAHARASHTRA','THE ZOROASTRIAN  BANK'),(37,'ZCBL0000012','119','DAHISAR','MUMBAI','MUMBAI','MAHARASHTRA','THE ZOROASTRIAN  BANK'),(38,'ZCBL0000013','119','THANE','MUMBAI','MUMBAI','MAHARASHTRA','THE ZOROASTRIAN  BANK');
